### ISSUE TITLE
插件与真寻bot超管控制插件冲突

### ISSUE THREAD

**Issue by 1717tian** [KarisAya/nonebot_plugin_groupmate_waifu#25]
![image](https://github.com/KarisAya/nonebot_plugin_groupmate_waifu/assets/63094351/6db4f33c-9ac1-41a6-ae90-4a66497972aa)
07-19 23:51:50 [ERROR] nonebot | Rule check failed for Matcher(type='message', module=extensive_plugin.nonebot_plugin_groupmate_waifu).                                                                                                         Traceback (most recent call last):                                                                                        File "D:\zhenxun_bot\bot.py", line 21, in <module>                                                                        nonebot.run()                                                                                                         File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\__init__.py", line 309, in run                                                                                         get_driver().run(*args, **kwargs)                                                                                     File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run                                                                                  uvicorn.run(                                                                                                          File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\uvicorn\main.py", line 568, in run                                                                                             server.run()                                                                                                          File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\uvicorn\server.py", line 59, in run                                                                                            return asyncio.run(self.serve(sockets=sockets))                                                                       File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run              return loop.run_until_complete(main)                                                                                  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete                                                                                                                  self.run_forever()                                                                                                    File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever                                                                                                                      super().run_forever()                                                                                                 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever                                                                                                                         self._run_once()                                                                                                      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once                                                                                                                          handle._run()                                                                                                         File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run              self._context.run(self._callback, *self._args)                                                                      > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\message.py", line 130, in _check_matcher                                                                               ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):                                        File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 303, in check_rule                                                                  return event_type == (cls.type or event_type) and await cls.rule(                                                     File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\internal\rule.py", line 73, in __call__                                                                                results = await asyncio.gather(                                                                                       File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 110, in __call__                                                                       return await run_sync(cast(Callable[..., R], self.call))(**values)                                                    File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.9\lib\site-packages\nonebot\utils.py", line 114, in _wrapper                                                                                       result = await loop.run_in_executor(None, pfunc)                                                                      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run                                                                                                                            result = self.fn(*self.args, **self.kwargs)                                                                           File "D:\zhenxun_bot\extensive_plugin\nonebot_plugin_groupmate_waifu\__init__.py", line 349, in <lambda>                  rule = lambda event:event.group_id in record_CP and record_CP[event.group_id].get(event.user_id,event.user_id) != event.user_id,                                                                                                            AttributeError: 'PrivateMessageEvent' object has no attribute 'group_id'                          

奇怪的bug.jpeg
已知情况：在超管插件关闭ex文件夹中的扩展插件时会引发上述报错
而关闭原有基础插件时则正常

**Comment by KarisAya** [comment]
修了
