### ISSUE TITLE
插件加载失败问题  系统：CentOS7  NB2：2.0.0b5

### ISSUE THREAD

**Issue by Ikaros-521** [KarisAya/nonebot_plugin_groupmate_waifu#6]
`
nonebot-adapter-onebot           2.1.3
nonebot-plugin-abbrreply         1.1.2
nonebot-plugin-alipayvoice       0.5.0
nonebot-plugin-analysis-bilibili 2.4.4
nonebot-plugin-apscheduler       0.2.0
nonebot-plugin-baidutranslate    0.1.1
nonebot-plugin-bangumi-search    1.0.1
nonebot-plugin-bilicover         0.2.0
nonebot-plugin-chatrecorder      0.1.8
nonebot-plugin-datastore         0.3.1
nonebot-plugin-ddcheck           0.1.14
nonebot-plugin-emojimix          0.1.8
nonebot-plugin-epicfree          0.1.9
nonebot-plugin-giyf              0.1.3
nonebot-plugin-groupmate-waifu   1.2.0
nonebot-plugin-gsmaterial        0.1.6
nonebot-plugin-htmlrender        0.2.0.1
nonebot-plugin-imageutils        0.1.8.1
nonebot-plugin-kawaii-robot      3.2.1
nonebot-plugin-localstore        0.1.0
nonebot-plugin-manager           0.5.9
nonebot-plugin-memes             0.3.3
nonebot-plugin-moegoe            0.5.2
nonebot-plugin-morning           0.3.1
nonebot-plugin-oddtext           0.1.1
nonebot-plugin-petpet            0.3.9
nonebot-plugin-qrcode            0.0.5
nonebot-plugin-russian-ban       1.0.1
nonebot-plugin-simplemusic       0.1.3
nonebot-plugin-status            0.4.0
nonebot-plugin-tarot             0.3.3
nonebot-plugin-what2eat          0.3.4
nonebot-plugin-withdraw          0.2.3
nonebot-plugin-wordcloud         0.2.4
`
报错
Traceback (most recent call last):
  File "/usr/local/python3/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/LX_Bot/./bot.py", line 32, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_groupmate_waifu/__init__.py", line 389, in <module>
    @scheduler.scheduled_job("cron",hour = 0)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/export.py", line 38, in __call__
    self[func.__name__] = func
AttributeError: 'str' object has no attribute '__name__'

**Comment by KarisAya** [comment]
定时插件版本太新了，把定时插件回退到2.0之前的版本

**Comment by Ikaros-521** [comment]
> 定时插件版本太新了，把定时插件回退到2.0之前的版本

感谢，换成0.1.4版本解决了
